// These are the image urls from Target website used to populate the carousels
const imageUrls = [
    'https://raw.githubusercontent.com/EZSteezy/FEC-Capstone-Bullseye/development/bullseye/src/components/carousel/images/1.webp',
    'https://raw.githubusercontent.com/EZSteezy/FEC-Capstone-Bullseye/development/bullseye/src/components/carousel/images/2.webp',
    'https://raw.githubusercontent.com/EZSteezy/FEC-Capstone-Bullseye/development/bullseye/src/components/carousel/images/3.webp',
    'https://raw.githubusercontent.com/EZSteezy/FEC-Capstone-Bullseye/development/bullseye/src/components/carousel/images/4.webp',
    'https://raw.githubusercontent.com/EZSteezy/FEC-Capstone-Bullseye/development/bullseye/src/components/carousel/images/5.webp',
    'https://raw.githubusercontent.com/EZSteezy/FEC-Capstone-Bullseye/development/bullseye/src/components/carousel/images/6.webp',
    'https://raw.githubusercontent.com/EZSteezy/FEC-Capstone-Bullseye/development/bullseye/src/components/carousel/images/7.webp',
    'https://raw.githubusercontent.com/EZSteezy/FEC-Capstone-Bullseye/development/bullseye/src/components/carousel/images/8.webp',
    'https://raw.githubusercontent.com/EZSteezy/FEC-Capstone-Bullseye/development/bullseye/src/components/carousel/images/9.webp',
    'https://raw.githubusercontent.com/EZSteezy/FEC-Capstone-Bullseye/development/bullseye/src/components/carousel/images/10.webp',
    'https://raw.githubusercontent.com/EZSteezy/FEC-Capstone-Bullseye/development/bullseye/src/components/carousel/images/11.webp',
    'https://raw.githubusercontent.com/EZSteezy/FEC-Capstone-Bullseye/development/bullseye/src/components/carousel/images/12.webp',
    'https://raw.githubusercontent.com/EZSteezy/FEC-Capstone-Bullseye/development/bullseye/src/components/carousel/images/13.webp',
    'https://raw.githubusercontent.com/EZSteezy/FEC-Capstone-Bullseye/development/bullseye/src/components/carousel/images/14.webp',
    'https://raw.githubusercontent.com/EZSteezy/FEC-Capstone-Bullseye/development/bullseye/src/components/carousel/images/15.webp',
    'https://raw.githubusercontent.com/EZSteezy/FEC-Capstone-Bullseye/development/bullseye/src/components/carousel/images/16.webp',
    'https://raw.githubusercontent.com/EZSteezy/FEC-Capstone-Bullseye/development/bullseye/src/components/carousel/images/17.webp',
    'https://raw.githubusercontent.com/EZSteezy/FEC-Capstone-Bullseye/development/bullseye/src/components/carousel/images/18.webp',
    'https://raw.githubusercontent.com/EZSteezy/FEC-Capstone-Bullseye/development/bullseye/src/components/carousel/images/19.webp',
    'https://raw.githubusercontent.com/EZSteezy/FEC-Capstone-Bullseye/development/bullseye/src/components/carousel/images/20.webp',
    'https://raw.githubusercontent.com/EZSteezy/FEC-Capstone-Bullseye/development/bullseye/src/components/carousel/images/21.webp',
    'https://raw.githubusercontent.com/EZSteezy/FEC-Capstone-Bullseye/development/bullseye/src/components/carousel/images/22.webp',
    'https://raw.githubusercontent.com/EZSteezy/FEC-Capstone-Bullseye/development/bullseye/src/components/carousel/images/23.webp',
    'https://raw.githubusercontent.com/EZSteezy/FEC-Capstone-Bullseye/development/bullseye/src/components/carousel/images/24.webp',
    'https://raw.githubusercontent.com/EZSteezy/FEC-Capstone-Bullseye/development/bullseye/src/components/carousel/images/25.webp',
    'https://raw.githubusercontent.com/EZSteezy/FEC-Capstone-Bullseye/development/bullseye/src/components/carousel/images/26.webp',
    'https://raw.githubusercontent.com/EZSteezy/FEC-Capstone-Bullseye/development/bullseye/src/components/carousel/images/27.webp',
    'https://raw.githubusercontent.com/EZSteezy/FEC-Capstone-Bullseye/development/bullseye/src/components/carousel/images/28.webp',
    'https://raw.githubusercontent.com/EZSteezy/FEC-Capstone-Bullseye/development/bullseye/src/components/carousel/images/29.webp',
    'https://raw.githubusercontent.com/EZSteezy/FEC-Capstone-Bullseye/development/bullseye/src/components/carousel/images/30.webp',
    'https://raw.githubusercontent.com/EZSteezy/FEC-Capstone-Bullseye/development/bullseye/src/components/carousel/images/31.webp',
    'https://raw.githubusercontent.com/EZSteezy/FEC-Capstone-Bullseye/development/bullseye/src/components/carousel/images/32.webp',
    'https://raw.githubusercontent.com/EZSteezy/FEC-Capstone-Bullseye/development/bullseye/src/components/carousel/images/33.webp',
    'https://raw.githubusercontent.com/EZSteezy/FEC-Capstone-Bullseye/development/bullseye/src/components/carousel/images/34.webp'
]

export default imageUrls;
