// These are the image urls from Target website used to populate the carousels
const imageUrls = [
    'https://i.ibb.co/ZLtBDBz/1.webp',
    'https://i.ibb.co/x5W0DXj/2.webp',
    'https://i.ibb.co/92ptZ7k/3.webp',
    'https://i.ibb.co/LScLpq0/4.webp',
    'https://i.ibb.co/V3PJZnn/5.webp',
    'https://i.ibb.co/wWfxBkd/6.webp',
    'https://i.ibb.co/jfXQ80X/7.webp',
    'https://i.ibb.co/RpnNH64/8.webp',
    'https://i.ibb.co/s6kfG5m/9.webp',
    'https://i.ibb.co/D5n8c4G/10.webp',
    'https://i.ibb.co/7bxky5X/11.webp',
    'https://i.ibb.co/gJR418g/12.webp',
    'https://i.ibb.co/VTkMjTJ/13.webp',
    'https://i.ibb.co/svn7vbK/14.webp',
    'https://i.ibb.co/bHf35jf/15.webp',
    'https://i.ibb.co/x5DKj0n/16.webp',
    'https://i.ibb.co/jWKJZ1K/17.webp',
    'https://i.ibb.co/bR7ZvMk/18.webp',
    'https://i.ibb.co/X7Dj5w4/19.webp',
    'https://i.ibb.co/899vBtk/20.webp',
    'https://i.ibb.co/yqGzxZt/21.webp',
    'https://i.ibb.co/zmWggnv/22.webp',
    'https://i.ibb.co/PjLkGs8/23.webp',
    'https://i.ibb.co/s3RRZQP/24.webp',
    'https://i.ibb.co/x5DKj0n/16.webp',
    'https://i.ibb.co/TLwH0xV/26.webp',
    'https://i.ibb.co/s6kfG5m/9.webp',
    'https://i.ibb.co/bPxcqjP/28.webp',
    'https://i.ibb.co/svn7vbK/14.webp',
    'https://i.ibb.co/rxNyL7k/30.webp',
    'https://i.ibb.co/VTkMjTJ/13.webp',
    'https://i.ibb.co/WNXZLm9/32.webp',
    'https://i.ibb.co/RpnNH64/8.webp',
    'https://i.ibb.co/7vB53TJ/34.webp'
]

export default imageUrls;
